name: EduardAPI
description: API de desenvolvimento de plugins que facilita sua vida
main: net.eduard.api.EduardAPI
version: 2.6.2
author: Eduard
authors: [Eduard]
softdepend: [HolographicDisplays,Citizens,Vault,Essentials,mcMMO,Factions]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  map:
    description: Controla a criacao de mapas
    aliases: [mapa]
    usage: /<command> help
  api:
    description: Controla plugins feitos pelo Edu
    aliases: [eduardapi,eduard,e]
    usage: /<command> help
  goto: 
    description: Teleporta para outro mundo
    aliases: [ir,irpara,mundo,world]
    usage: /<command> <world>
  enchantment: 
    description: Encanta o item para um nivel
    aliases: [ench]
    usage: /<command> <enchant> <level>
  sound: 
    description: Toca um som do minecraft
    aliases: [som]
    usage: /<command> <sound> [volume] [pitch]
  setexperience: 
    description: 
    aliases: [setexp,setxp]
    usage: /<command> <xp>