

debug-bungee-bukkit: false

debug-storage: false

debug-copyable: false

debug-commands: false

debug-menu: false

debug-replacers: false

debug-db: false


skins: false
custom-skin: "EduardKillerPro"

player target: "$player_name - $player_level"
stack-design: "§aQuantidade: §f$stack"

money-format: "###,###.##"
money-format-locale: "PT-BR"

no-join-message: true
custom-join-message: false
on-join-message: '&6O jogador &e$player &6entrou no server'

no-quit-message: true
custom-quit-message: false
on-quit-message: '&6O jogador &e$player &6saiu do server'

no-death-message: true
custom-death-message: false
on-death-player-message: '&6O jogador &e$killer matou o jogador $player'

custom-first-join-message: false
first-join-message: ""

custom-motd: false

custom-motd-amount: -1
motd:
- seja bem vindo
- Ao meu servidor!

auto-respawn: false
auto-rejoin: false

commands-blocked:
- /comandobloqueado


